// ============================================================================
// 🦁 USELESS ZOO EXPLORER - DATA REPOSITORY
// Certified 0% Scientifically Accurate • Proudly Useless
// ============================================================================

const ANIMALS = [
  {
    id: "lion",
    name: "Lion",
    emoji: "🦁",
    category: "jungle",
    fakeScientificName: "Panthera snackus",
    badge: "King of the Living Room Rug",
    fakeWeight: "Approximately 17 refrigerators",
    fakeHeight: "3.7 Wi-Fi routers",
    fakeSpeed: "Fast enough to catch a falling biscuit",
    fakeDiet: "Pizza, clouds and occasionally grass",
    fakeHabitat: "Luxury grasslands and under sofa cushions",
    fakeLifespan: "Until somebody says 'Who's a good kitty?'",
    funnyFact: "Scientists believe the lion's mane is primarily used to hide unfinished homework and extra snacks.",
    specialAbility: "Can roar loud enough to wake a sleeping potato across three time zones.",
    favoriteActivity: "Taking 23-hour naps and pretending to supervise the savannah.",
    favoriteHobby: "Judging passing gazelles on their fashion choices.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐ (Too much glorious hair)",
    brainPower: "87% roaring, 13% thinking about lunch",
    stats: {
      intelligence: "73 potatoes",
      sleepiness: 94,
      pizzaCompatibility: 99,
      gamingSkill: 42,
      teaResistance: "Very questionable",
      wifiDependency: "Extreme",
      dancingAbility: "Terrible hip hop, decent salsa"
    },
    scientificConfidence: 3.2,
    comparisonStats: {
      roaringPower: 98,
      snackCapacity: 88,
      napAbility: 99,
      danceSkill: 35,
      wifiStrength: 75,
      homeworkAvoidance: 92,
      randomness: 60,
      hatCompatibility: 12,
      formalwear: 45
    }
  },
  {
    id: "elephant",
    name: "Elephant",
    emoji: "🐘",
    category: "jungle",
    fakeScientificName: "Elephantus Giganticus Probably",
    badge: "Password Amnesia Specialist",
    fakeWeight: "Approximately 4,000 bananas",
    fakeHeight: "9 shopping carts stacked clumsily",
    fakeSpeed: "Depends entirely on local Wi-Fi signal",
    fakeDiet: "Grass, leaves and suspicious-looking sandwiches",
    fakeHabitat: "Anywhere with sufficient room to forget car keys",
    fakeLifespan: "Forever, unless startled by a very small grape",
    funnyFact: "Elephants have excellent memories for drama that happened in 2004, but cannot remember why they entered the kitchen.",
    specialAbility: "Can remember absolutely everything except their email passwords.",
    favoriteActivity: "Forgetting where they parked their compact hybrid hatchback.",
    favoriteHobby: "Using trunk as an unruly garden hose at weddings.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐⭐☆ (Requires a parachute with ear holes)",
    brainPower: "60% old grudges, 40% wanting peanuts",
    stats: {
      intelligence: "412 roasted peanuts",
      sleepiness: 68,
      pizzaCompatibility: 91,
      gamingSkill: 18,
      teaResistance: "Immune to chamomile",
      wifiDependency: "Severe (streams 4K nature documentaries)",
      dancingAbility: "Earthquake tier"
    },
    scientificConfidence: 1.8,
    comparisonStats: {
      roaringPower: 70,
      snackCapacity: 100,
      napAbility: 80,
      danceSkill: 22,
      wifiStrength: 85,
      homeworkAvoidance: 88,
      randomness: 45,
      hatCompatibility: 25,
      formalwear: 65
    }
  },
  {
    id: "giraffe",
    name: "Giraffe",
    emoji: "🦒",
    category: "jungle",
    fakeScientificName: "Longneckus Whysohigh",
    badge: "Biological Weather Satellite",
    fakeWeight: "One small scenic mountain",
    fakeHeight: "Approximately 12 ceiling fans",
    fakeSpeed: "Speed of a runaway skyscraper",
    fakeDiet: "Leaves located inconveniently far away from the ground",
    fakeHabitat: "Tall areas and high-ceiling penthouses",
    fakeLifespan: "3,000 meters of neck growth",
    funnyFact: "Giraffes don't sleep; they just fold their necks into origami swans and hope nobody asks questions.",
    specialAbility: "Can inspect tomorrow's weather forecast by simply looking over cloud cover.",
    favoriteActivity: "Peeking into second-story hotel bathrooms by complete accident.",
    favoriteHobby: "Playing competitive basketball without jumping.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐ (Need a crane to put it on)",
    brainPower: "92% calculating wind resistance on forehead, 8% chewing",
    stats: {
      intelligence: "84 ceiling tiles",
      sleepiness: 34,
      pizzaCompatibility: 78,
      gamingSkill: 55,
      teaResistance: "Takes 45 minutes to swallow hot tea",
      wifiDependency: "Acts as a cellular 5G tower",
      dancingAbility: "Wobbly noodle shuffle"
    },
    scientificConfidence: 4.1,
    comparisonStats: {
      roaringPower: 15,
      snackCapacity: 75,
      napAbility: 30,
      danceSkill: 40,
      wifiStrength: 100,
      homeworkAvoidance: 70,
      randomness: 72,
      hatCompatibility: 5,
      formalwear: 80
    }
  },
  {
    id: "penguin",
    name: "Penguin",
    emoji: "🐧",
    category: "cold",
    fakeScientificName: "Penguinus Formalwearus",
    badge: "Permanently Dressed for Gala",
    fakeWeight: "27 artisanal ice cubes",
    fakeHeight: "1.2 bowling pins",
    fakeSpeed: "Depends on belly sliding friction coefficient",
    fakeDiet: "Fish, slushies and frozen ramen noodles",
    fakeHabitat: "Antarctica corporate boardroom",
    fakeLifespan: "As long as the tuxedo remains dry-cleaned",
    funnyFact: "Penguins are not flightless birds; they have simply signed an oath never to fly because walking like a toddler is funnier.",
    specialAbility: "Can attend high-level United Nations diplomatic summits without RSVPing.",
    favoriteActivity: "Sliding on belly directly into personal embarrassment.",
    favoriteHobby: "Complaining that the freezer is 'too tropical'.",
    difficultyFindingHat: "⭐⭐☆☆☆☆☆☆☆☆ (Bowler hats fit quite handsomely)",
    brainPower: "50% looking sharp, 50% craving anchovies",
    stats: {
      intelligence: "91 chilled oysters",
      sleepiness: 55,
      pizzaCompatibility: 62,
      gamingSkill: 84,
      teaResistance: "Requires Iced Earl Grey exclusively",
      wifiDependency: "Very Low (relies on frozen Morse code)",
      dancingAbility: "Tap dance master"
    },
    scientificConfidence: 2.7,
    comparisonStats: {
      roaringPower: 25,
      snackCapacity: 60,
      napAbility: 50,
      danceSkill: 95,
      wifiStrength: 30,
      homeworkAvoidance: 85,
      randomness: 65,
      hatCompatibility: 90,
      formalwear: 100
    }
  },
  {
    id: "tiger",
    name: "Tiger",
    emoji: "🐯",
    category: "jungle",
    fakeScientificName: "Tigerus Verystripy",
    badge: "Barcode Enthusiast",
    fakeWeight: "Approximately 43 school backpacks",
    fakeHeight: "6 overturned skateboards",
    fakeSpeed: "Faster than an overdue library book reminder",
    fakeDiet: "Spicy curry, clouds and occasionally deer",
    fakeHabitat: "Dense bamboo thickets with good acoustics",
    fakeLifespan: "Until someone asks it to vacuum the living room",
    funnyFact: "Every tiger's barcode can be scanned at supermarkets to discount a box of frosted flakes.",
    specialAbility: "Can instantly vanish into thin air the exact moment someone mentions doing homework.",
    favoriteActivity: "Counting its stripes and losing count around forty-seven.",
    favoriteHobby: "Practicing dramatic slow-motion walks in front of mirrors.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐☆☆☆☆ (Ears puncture every fedora)",
    brainPower: "70% stalking leaves, 30% thinking it's an orange housecat",
    stats: {
      intelligence: "68 laser pointers",
      sleepiness: 86,
      pizzaCompatibility: 94,
      gamingSkill: 65,
      teaResistance: "Refuses tea, drinks melted butter",
      wifiDependency: "Moderate",
      dancingAbility: "Fierce runway strut"
    },
    scientificConfidence: 0.9,
    comparisonStats: {
      roaringPower: 92,
      snackCapacity: 82,
      napAbility: 88,
      danceSkill: 60,
      wifiStrength: 60,
      homeworkAvoidance: 99,
      randomness: 55,
      hatCompatibility: 30,
      formalwear: 60
    }
  },
  {
    id: "panda",
    name: "Panda",
    emoji: "🐼",
    category: "jungle",
    fakeScientificName: "Bambous Confusus",
    badge: "Certified Physics Defier",
    fakeWeight: "22 fluffy duvet covers",
    fakeHeight: "3 stackable plastic stools",
    fakeSpeed: "Rolling speed: 40 km/h; Walking speed: 0.2 km/h",
    fakeDiet: "99.9% bamboo sticks, 0.1% wondering what bamboo tastes like",
    fakeHabitat: "Wherever they accidentally roll down a hill",
    fakeLifespan: "Indefinite, sustained purely by tumbling clumsiness",
    funnyFact: "Scientists confirmed pandas were originally black and white because they ran out of colored ink during printing.",
    specialAbility: "Can fall down an entire flight of stairs and consider it a refreshing workout.",
    favoriteActivity: "Sneezing with explosive force and scaring own offspring.",
    favoriteHobby: "Rolling downhill like an oversized bowling ball.",
    difficultyFindingHat: "⭐⭐⭐⭐☆☆☆☆☆☆ (Head too spherical, hat slides off)",
    brainPower: "10% eating, 90% gentle tumbling confusion",
    stats: {
      intelligence: "14 soggy bamboo shoots",
      sleepiness: 98,
      pizzaCompatibility: 88,
      gamingSkill: 20,
      teaResistance: "Brews bamboo leaf tea daily",
      wifiDependency: "Zero (unaware electricity exists)",
      dancingAbility: "Somersaulting potato"
    },
    scientificConfidence: 3.8,
    comparisonStats: {
      roaringPower: 30,
      snackCapacity: 95,
      napAbility: 98,
      danceSkill: 40,
      wifiStrength: 10,
      homeworkAvoidance: 95,
      randomness: 90,
      hatCompatibility: 40,
      formalwear: 50
    }
  },
  {
    id: "sloth",
    name: "Sloth",
    emoji: "🦥",
    category: "jungle",
    fakeScientificName: "Speedus Zero-us",
    badge: "Speed Limit: 0.001 mph",
    fakeWeight: "Half a sack of wet moss",
    fakeHeight: "1 coat hanger",
    fakeSpeed: "Takes 3 business days to blink left eye",
    fakeDiet: "Fermented tree lint and very patient leaves",
    fakeHabitat: "Upside-down tree branches in slow motion",
    fakeLifespan: "Nobody knows because they haven't finished their first lap",
    funnyFact: "Sloths are actually capable of running at 60 mph, but they find human hurry quite tacky.",
    specialAbility: "Can make a 3-minute microwave meal feel like a historical dynasty.",
    favoriteActivity: "Thinking about moving to a different branch, then taking a nap instead.",
    favoriteHobby: "Holding staring contests with moss and losing.",
    difficultyFindingHat: "⭐⭐☆☆☆☆☆☆☆☆ (Wears anything that falls on its head)",
    brainPower: "2% operating vitals, 98% buffering...",
    stats: {
      intelligence: "3 sleepy avocados",
      sleepiness: 100,
      pizzaCompatibility: 40,
      gamingSkill: 2,
      teaResistance: "Tea cools down before sloth takes first sip",
      wifiDependency: "Dial-up 56k speed in brain",
      dancingAbility: "Statue mimicry"
    },
    scientificConfidence: 0.4,
    comparisonStats: {
      roaringPower: 5,
      snackCapacity: 30,
      napAbility: 100,
      danceSkill: 5,
      wifiStrength: 5,
      homeworkAvoidance: 100,
      randomness: 20,
      hatCompatibility: 70,
      formalwear: 20
    }
  },
  {
    id: "duck",
    name: "Duck",
    emoji: "🦆",
    category: "birds",
    fakeScientificName: "Honkus Breadseeker",
    badge: "Waterproof Terror of the Pond",
    fakeWeight: "4 baguettes",
    fakeHeight: "1 standing thermos",
    fakeSpeed: "Mach 3 when someone rustles a plastic bread bag",
    fakeDiet: "Stale sourdough, French fries, and absolute vengeance",
    fakeHabitat: "Ponds and middle of quiet golf tournaments",
    fakeLifespan: "Until all bread crumbs have been seized",
    funnyFact: "Ducks do not actually quack; they speak ancient Latin poetry backwards to summon more baguettes.",
    specialAbility: "Can detect a single crumb dropping from a distance of 14 miles.",
    favoriteActivity: "Aggressively staring at people eating picnics.",
    favoriteHobby: "Floating effortlessly while legs pedal like a nuclear generator under water.",
    difficultyFindingHat: "⭐⭐⭐☆☆☆☆☆☆☆ (Looks dapper in tiny top hats)",
    brainPower: "99% bread radar, 1% honk",
    stats: {
      intelligence: "88 sourdough starter jars",
      sleepiness: 45,
      pizzaCompatibility: 99,
      gamingSkill: 77,
      teaResistance: "Dips whole head in tea mug",
      wifiDependency: "High (browsing bakery stock markets)",
      dancingAbility: "Head-bobbing hip hop"
    },
    scientificConfidence: 2.1,
    comparisonStats: {
      roaringPower: 80,
      snackCapacity: 98,
      napAbility: 45,
      danceSkill: 80,
      wifiStrength: 70,
      homeworkAvoidance: 80,
      randomness: 92,
      hatCompatibility: 85,
      formalwear: 70
    }
  },
  {
    id: "snail",
    name: "Snail",
    emoji: "🐌",
    category: "nobody_asked",
    fakeScientificName: "Turbo Slimepack",
    badge: "Homeownership World Champion",
    fakeWeight: "0.003 feather pillows",
    fakeHeight: "Half a thimble",
    fakeSpeed: "4 inches per geological epoch",
    fakeDiet: "Dewdrops, fancy lettuce, and existential dread",
    fakeHabitat: "Sidewalks precisely when you are in a rush",
    fakeLifespan: "Long enough to cross one suburban driveway",
    funnyFact: "Snails are surprisingly fast if you measure their speed relative to continental drift.",
    specialAbility: "Carries a fully furnished 2-bedroom mortgage-free condo on its back.",
    favoriteActivity: "Leaving a glittering silver highway that leads nowhere important.",
    favoriteHobby: "Taking 48 hours to cross a garden pebble.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐☆☆ (Hats unbalance the entire shell)",
    brainPower: "50% slime production, 50% GPS recalibration",
    stats: {
      intelligence: "2 garden peas",
      sleepiness: 90,
      pizzaCompatibility: 25,
      gamingSkill: 10,
      teaResistance: "Dissolves into a puddle if tea has salt",
      wifiDependency: "Zero latency because it doesn't move",
      dancingAbility: "Slow motion breakdance"
    },
    scientificConfidence: 1.2,
    comparisonStats: {
      roaringPower: 1,
      snackCapacity: 15,
      napAbility: 95,
      danceSkill: 15,
      wifiStrength: 20,
      homeworkAvoidance: 90,
      randomness: 40,
      hatCompatibility: 30,
      formalwear: 35
    }
  },
  {
    id: "crocodile",
    name: "Crocodile",
    emoji: "🐊",
    category: "water",
    fakeScientificName: "Luggageus Pointytooth",
    badge: "Disguised Floating Log",
    fakeWeight: "84 leather suitcases",
    fakeHeight: "1 surfboard with teeth",
    fakeSpeed: "0 mph while sunbathing; 900 mph when someone drops a hot dog",
    fakeDiet: "River fish, algae and accidental flip-flops",
    fakeHabitat: "Muddy swamps and murky riverbanks with free tanning beds",
    fakeLifespan: "Has been grumpy since the Jurassic era",
    funnyFact: "Crocodiles only open their mouths wide to receive automatic dental software updates from passing birds.",
    specialAbility: "Can float motionless pretending to be a rotting piece of wood for 11 months.",
    favoriteActivity: "Crying fake tears when someone burns the toast.",
    favoriteHobby: "Sunbathing on mud and scaring kayakers for fun.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐⭐☆ (Snout eats the hat before mirror check)",
    brainPower: "80% log simulation, 20% snap",
    stats: {
      intelligence: "39 swamp logs",
      sleepiness: 88,
      pizzaCompatibility: 85,
      gamingSkill: 40,
      teaResistance: "Immune to scalding river mud",
      wifiDependency: "Submersible 4G antenna tail",
      dancingAbility: "Death roll waltz"
    },
    scientificConfidence: 3.5,
    comparisonStats: {
      roaringPower: 85,
      snackCapacity: 92,
      napAbility: 85,
      danceSkill: 50,
      wifiStrength: 45,
      homeworkAvoidance: 95,
      randomness: 65,
      hatCompatibility: 15,
      formalwear: 40
    }
  },
  {
    id: "chicken",
    name: "Chicken",
    emoji: "🐔",
    category: "birds",
    fakeScientificName: "Dinosaurus Micro-Editioum",
    badge: "Living Miniature T-Rex",
    fakeWeight: "1 bowling ball and a handful of feathers",
    fakeHeight: "2 coffee pots",
    fakeSpeed: "Pure frantic zigzag panic velocity",
    fakeDiet: "Corn kernels, shiny foil wrappers, and small rocks for dessert",
    fakeHabitat: "Backyard coops and the other side of the road",
    fakeLifespan: "Determined by why it crossed the road",
    funnyFact: "Chickens remember the exact dinosaur reign when their ancestors terrorized the planet and they are still plotting their revenge.",
    specialAbility: "Head stays completely locked in space like a military gyro-stabilizer.",
    favoriteActivity: "Crossing roads without valid pedestrian permits.",
    favoriteHobby: "Clucking aggressively at harmless fallen leaves.",
    difficultyFindingHat: "⭐⭐⭐⭐☆☆☆☆☆☆ (Little red comb acts as natural beret)",
    brainPower: "3% memory, 97% 'IS THAT A WORM?!'",
    stats: {
      intelligence: "15 cracked corn bits",
      sleepiness: 40,
      pizzaCompatibility: 75,
      gamingSkill: 60,
      teaResistance: "Pours tea on ground to peck at mug",
      wifiDependency: "High (checking egg stock futures)",
      dancingAbility: "The Chicken Dance champion"
    },
    scientificConfidence: 1.5,
    comparisonStats: {
      roaringPower: 65,
      snackCapacity: 70,
      napAbility: 35,
      danceSkill: 88,
      wifiStrength: 50,
      homeworkAvoidance: 75,
      randomness: 99,
      hatCompatibility: 65,
      formalwear: 55
    }
  },
  {
    id: "monkey",
    name: "Monkey",
    emoji: "🐒",
    category: "jungle",
    fakeScientificName: "Officus Primatus",
    badge: "Senior Chaos Consultant",
    fakeWeight: "15 fruit salads",
    fakeHeight: "2 office chairs",
    fakeSpeed: "Fast enough to steal your sunglasses before you blink",
    fakeDiet: "Bananas, stolen tourists' potato chips, and iced macchiatos",
    fakeHabitat: "Tree canopies and disorganized corporate open-plan desks",
    fakeLifespan: "As long as there are sunglasses to snatch",
    funnyFact: "If you give a monkey an office laptop, it will reply-all to company emails and accidentally get promoted to Vice President.",
    specialAbility: "Can peel a banana with its toes while sending confused emojis to LinkedIn.",
    favoriteActivity: "Throwing fruit at tourists who ask dumb questions.",
    favoriteHobby: "Swinging from ceiling fans like a dramatic Broadway stuntman.",
    difficultyFindingHat: "⭐☆☆☆☆☆☆☆☆☆ (Steals tourist hats instantly)",
    brainPower: "90% mischief plotting, 10% banana location caching",
    stats: {
      intelligence: "190 ripe bananas",
      sleepiness: 30,
      pizzaCompatibility: 98,
      gamingSkill: 92,
      teaResistance: "Throws tea cup at wall, drinks milk",
      wifiDependency: "Needs fiber-optic 10Gbps to stream memes",
      dancingAbility: "Macarena world finalist"
    },
    scientificConfidence: 2.9,
    comparisonStats: {
      roaringPower: 75,
      snackCapacity: 89,
      napAbility: 25,
      danceSkill: 92,
      wifiStrength: 95,
      homeworkAvoidance: 98,
      randomness: 95,
      hatCompatibility: 98,
      formalwear: 70
    }
  },
  {
    id: "frog",
    name: "Frog",
    emoji: "🐸",
    category: "water",
    fakeScientificName: "Kermitus Dramaticus",
    badge: "Amphibious Spring Loaded Toy",
    fakeWeight: "1 damp tennis ball",
    fakeHeight: "1 teacup saucer",
    fakeSpeed: "Zero to orbit in 0.04 seconds",
    fakeDiet: "Flies, mosquitoes, and morning pond morning dew",
    fakeHabitat: "Lily pads with scenic acoustic echo",
    fakeLifespan: "Until it kisses a prince and gets disappointed",
    funnyFact: "Frogs swallow food by pulling their eyeballs down into their mouth to physically push down the snack.",
    specialAbility: "Can sit completely unbothered on a wet leaf while contemplating the universe.",
    favoriteActivity: "Croaking at 3:15 AM precisely when you're trying to sleep.",
    favoriteHobby: "Catching flies in midair with a 4-foot elastic tongue.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐☆☆☆☆ (Moisture ruins fedora felting)",
    brainPower: "5% ribbit, 95% sticky tongue hydraulics",
    stats: {
      intelligence: "22 pond lily seeds",
      sleepiness: 60,
      pizzaCompatibility: 65,
      gamingSkill: 70,
      teaResistance: "Baths directly in lukewarm chamomile",
      wifiDependency: "Low",
      dancingAbility: "Leapfrog breakdance"
    },
    scientificConfidence: 3.1,
    comparisonStats: {
      roaringPower: 50,
      snackCapacity: 65,
      napAbility: 60,
      danceSkill: 85,
      wifiStrength: 35,
      homeworkAvoidance: 80,
      randomness: 88,
      hatCompatibility: 55,
      formalwear: 45
    }
  },
  {
    id: "zebra",
    name: "Zebra",
    emoji: "🦓",
    category: "jungle",
    fakeScientificName: "Equus Pyjamasus",
    badge: "Optical Illusion Stallion",
    fakeWeight: "35 rolled-up mattresses",
    fakeHeight: "7 skate ramps",
    fakeSpeed: "Optical illusion velocity (appears stationary while sprinting)",
    fakeDiet: "Savannah grass and striped peppermint candies",
    fakeHabitat: "Black-and-white television broadcasts and grasslands",
    fakeLifespan: "Until the stripes fade in the wash",
    funnyFact: "Scientists have conclusively proven zebras are just regular horses wearing striped silk pajamas.",
    specialAbility: "Can blind predators through sheer optical barcode dazzle.",
    favoriteActivity: "Arguing with other zebras about who has the slimmer stripes.",
    favoriteHobby: "Posing next to pedestrian zebra crossings to cause gridlock.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐☆☆☆☆☆ (Must match stripe orientation)",
    brainPower: "40% grass grazing, 60% monochrome philosophy",
    stats: {
      intelligence: "85 barcode lines",
      sleepiness: 50,
      pizzaCompatibility: 70,
      gamingSkill: 50,
      teaResistance: "Prefers zebra stripe licorice tea",
      wifiDependency: "Medium",
      dancingAbility: "Galloping tap dance"
    },
    scientificConfidence: 4.8,
    comparisonStats: {
      roaringPower: 45,
      snackCapacity: 80,
      napAbility: 55,
      danceSkill: 75,
      wifiStrength: 65,
      homeworkAvoidance: 75,
      randomness: 70,
      hatCompatibility: 50,
      formalwear: 90
    }
  },
  {
    id: "kangaroo",
    name: "Kangaroo",
    emoji: "🦘",
    category: "nobody_asked",
    fakeScientificName: "Boingus Pouchicus",
    badge: "Biological Pogo Stick",
    fakeWeight: "14 trampoline springs",
    fakeHeight: "1 tall lamppost",
    fakeSpeed: "Boing... Boing... 55 km/h",
    fakeDiet: "Shrubs, dry twigs, and spilled protein shakes",
    fakeHabitat: "Australian outback and boxing gyms",
    fakeLifespan: "Countless rebounds",
    funnyFact: "The kangaroo pouch was originally designed to carry spare smartphone chargers and sunglasses.",
    specialAbility: "Can launch a dropkick powerful enough to send an asteroid into solar orbit.",
    favoriteActivity: "Flexing biceps while staring intensely at innocent tourists.",
    favoriteHobby: "Hiding TV remotes in front pouch.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐☆☆☆☆ (Flies off on the first high jump)",
    brainPower: "75% bounce mechanics, 25% gym bro mindset",
    stats: {
      intelligence: "110 protein bars",
      sleepiness: 45,
      pizzaCompatibility: 82,
      gamingSkill: 65,
      teaResistance: "Immune to eucalyptus brew",
      wifiDependency: "Low",
      dancingAbility: "Aerobics jump master"
    },
    scientificConfidence: 2.4,
    comparisonStats: {
      roaringPower: 60,
      snackCapacity: 85,
      napAbility: 40,
      danceSkill: 82,
      wifiStrength: 50,
      homeworkAvoidance: 70,
      randomness: 75,
      hatCompatibility: 45,
      formalwear: 50
    }
  },
  {
    id: "turtle",
    name: "Turtle",
    emoji: "🐢",
    category: "water",
    fakeScientificName: "Mobile Shellicus",
    badge: "Armored Patience Overlord",
    fakeWeight: "1 military grade bunker",
    fakeHeight: "1 overturned wok pan",
    fakeSpeed: "Slower than a government committee approval",
    fakeDiet: "Waterweed, jellyfish, and 300-year-old family recipes",
    fakeHabitat: "Oceans and warm rocks with sunny exposure",
    fakeLifespan: "Older than the Roman Empire and still going",
    funnyFact: "Turtles breathe through their tails when they are too lazy to poke their heads above water.",
    specialAbility: "Can withdraw entire head into shell whenever conversations become awkward.",
    favoriteActivity: "Outliving everyone who gave them bad financial advice.",
    favoriteHobby: "Taking 4 hours to chew a single lettuce leaf.",
    difficultyFindingHat: "⭐⭐☆☆☆☆☆☆☆☆ (Shell is basically a body hat)",
    brainPower: "10% swimming, 90% contemplating centuries gone by",
    stats: {
      intelligence: "320 ancient scrolls",
      sleepiness: 82,
      pizzaCompatibility: 60,
      gamingSkill: 15,
      teaResistance: "Enjoys boiling kelp infusion",
      wifiDependency: "Zero (uses carrier pigeons)",
      dancingAbility: "Underwater slow-mo groove"
    },
    scientificConfidence: 3.9,
    comparisonStats: {
      roaringPower: 5,
      snackCapacity: 60,
      napAbility: 92,
      danceSkill: 30,
      wifiStrength: 10,
      homeworkAvoidance: 100,
      randomness: 30,
      hatCompatibility: 60,
      formalwear: 65
    }
  },
  {
    id: "parrot",
    name: "Parrot",
    emoji: "🦜",
    category: "birds",
    fakeScientificName: "Repeatocrazy Chattybox",
    badge: "Feathered Audio Recorder",
    fakeWeight: "2 tropical pineapples",
    fakeHeight: "1 standing blender",
    fakeSpeed: "Faster than juicy neighborhood gossip",
    fakeDiet: "Sunflower seeds, fruit slices, and private family secrets",
    fakeHabitat: "Rainforests and pirate captains' left shoulders",
    fakeLifespan: "Long enough to learn every swear word in 14 languages",
    funnyFact: "Parrots do not actually talk; they merely replay intercepted Russian satellite frequencies with high pitch.",
    specialAbility: "Can mimic a microwave doorbell ring so accurately that family members check the kitchen 18 times.",
    favoriteActivity: "Shouting private Wi-Fi passwords when company visits.",
    favoriteHobby: "Pretending to be an antique car alarm at 6:00 AM on Sunday.",
    difficultyFindingHat: "⭐⭐⭐☆☆☆☆☆☆☆ (Looks sharp in miniature pirate tricorn)",
    brainPower: "95% audio playback buffer, 5% feather grooming",
    stats: {
      intelligence: "140 cassette tapes",
      sleepiness: 25,
      pizzaCompatibility: 75,
      gamingSkill: 78,
      teaResistance: "Sips cold fruit tea with drama",
      wifiDependency: "Bluetooth 5.3 embedded in beak",
      dancingAbility: "Head-banging disco legend"
    },
    scientificConfidence: 1.6,
    comparisonStats: {
      roaringPower: 88,
      snackCapacity: 65,
      napAbility: 20,
      danceSkill: 90,
      wifiStrength: 85,
      homeworkAvoidance: 80,
      randomness: 94,
      hatCompatibility: 88,
      formalwear: 80
    }
  },
  {
    id: "unicorn",
    name: "Unicorn",
    emoji: "🦄",
    category: "nobody_asked",
    fakeScientificName: "Equus Sparklepoint",
    badge: "100% Definitely Real Specimen",
    fakeWeight: "800 cotton candy clouds",
    fakeHeight: "4 iridescent rainbow arcs",
    fakeSpeed: "Speed of light filtered through glitter",
    fakeDiet: "Morning dew, stardust, and strawberry cupcakes",
    fakeHabitat: "Enchanted glades and teenage notebook covers",
    fakeLifespan: "Permanent until someone stops believing",
    funnyFact: "Unicorn horns are actually Wi-Fi repeaters designed by mythical elves to provide free internet to woodland creatures.",
    specialAbility: "Can sneeze pure rainbow glitter that takes 3 weeks to vacuum from upholstery.",
    favoriteActivity: "Failing to blend in with regular farm horses.",
    favoriteHobby: "Charging smartphones using forehead horn.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐ (Horn rips straight through the crown)",
    brainPower: "80% sparkle generation, 20% avoiding taxes",
    stats: {
      intelligence: "777 rainbow prisms",
      sleepiness: 40,
      pizzaCompatibility: 100,
      gamingSkill: 99,
      teaResistance: "Immune to sparkling jasmine glitter tea",
      wifiDependency: "Is the server",
      dancingAbility: "Ballet with fireworks"
    },
    scientificConfidence: 0.1,
    comparisonStats: {
      roaringPower: 50,
      snackCapacity: 90,
      napAbility: 45,
      danceSkill: 100,
      wifiStrength: 100,
      homeworkAvoidance: 100,
      randomness: 98,
      hatCompatibility: 1,
      formalwear: 95
    }
  },
  {
    id: "dinosaur",
    name: "Dinosaur",
    emoji: "🦖",
    category: "nobody_asked",
    fakeScientificName: "Definitely Aliveicus",
    badge: "Meteor Survivor (Self-Reported)",
    fakeWeight: "64 city buses and a forklift",
    fakeHeight: "3 office complexes",
    fakeSpeed: "Stomping speed: 1 earthquake per minute",
    fakeDiet: "Entire grocery stores and chocolate pudding cups",
    fakeHabitat: "Suburban cul-de-sacs pretending to be Jurassic era",
    fakeLifespan: "65 million years and still waiting for bus",
    funnyFact: "The T-Rex's tiny arms were not an evolutionary mistake; they were optimized for holding tiny coffee cups without spilling.",
    specialAbility: "Cannot make its own bed because arms cannot reach the pillows.",
    favoriteActivity: "Roaring so loud car alarms activate in adjacent zip codes.",
    favoriteHobby: "Trying and failing to do a single push-up.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐☆☆ (Needs a billboard strapped to forehead)",
    brainPower: "90% roar impulse, 10% frustration with short arms",
    stats: {
      intelligence: "2 walnuts and a boulder",
      sleepiness: 50,
      pizzaCompatibility: 100,
      gamingSkill: 5,
      teaResistance: "Drinks boiling lava",
      wifiDependency: "Cannot press phone buttons due to claws",
      dancingAbility: "Ground-shaking mosh pit"
    },
    scientificConfidence: 0.05,
    comparisonStats: {
      roaringPower: 100,
      snackCapacity: 100,
      napAbility: 60,
      danceSkill: 30,
      wifiStrength: 20,
      homeworkAvoidance: 100,
      randomness: 85,
      hatCompatibility: 20,
      formalwear: 30
    }
  },
  {
    id: "fish",
    name: "Fish",
    emoji: "🐟",
    category: "water",
    fakeScientificName: "Swimmus Neverbicyclus",
    badge: "Hydrodynamic Amnesiac",
    fakeWeight: "0.2 soggy sponges",
    fakeHeight: "1 butter knife",
    fakeSpeed: "Fast in water, 0.0 mph on an exercise bicycle",
    fakeDiet: "Water flakes and bubbles that look like friends",
    fakeHabitat: "Freshwater aquariums and dentist office lobbies",
    fakeLifespan: "Resets every 3 seconds",
    funnyFact: "Fish are world-class swimmers, but universally terrible at parallel parking bicycles.",
    specialAbility: "Can forget what it was doing halfway through swimming across a 6-inch fishbowl.",
    favoriteActivity: "Staring blankly at aquarium castle figurines.",
    favoriteHobby: "Blowing bubbles and being surprised every single time.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐⭐☆ (Hat gets completely soaked and floats away)",
    brainPower: "3-second RAM cache with zero persistent storage",
    stats: {
      intelligence: "1 bubble",
      sleepiness: 20,
      pizzaCompatibility: 12,
      gamingSkill: 15,
      teaResistance: "Entire existence is swimming in lukewarm herbal water",
      wifiDependency: "Needs waterproof fiber connection",
      dancingAbility: "Synchronized bubble sway"
    },
    scientificConfidence: 1.1,
    comparisonStats: {
      roaringPower: 1,
      snackCapacity: 40,
      napAbility: 50,
      danceSkill: 65,
      wifiStrength: 15,
      homeworkAvoidance: 85,
      randomness: 90,
      hatCompatibility: 10,
      formalwear: 25
    }
  },
  {
    id: "hippo",
    name: "Hippopotamus",
    emoji: "🦛",
    category: "water",
    fakeScientificName: "River Tankus Submersus",
    badge: "Heavy Artillery Potato",
    fakeWeight: "900 watermelons",
    fakeHeight: "1 standard minivan",
    fakeSpeed: "Runs faster on underwater riverbeds than Usain Bolt",
    fakeDiet: "Whole cabbages, mud shakes, and misplaced pride",
    fakeHabitat: "Murky river spas and African jacuzzi basins",
    fakeLifespan: "Until it runs out of river mud sunscreen",
    funnyFact: "Hippos secrete their own natural pink sunscreen, which scientists believe also smells lightly of strawberry milkshake.",
    specialAbility: "Can yawn so wide it creates a localized vacuum that swallows floating plastic toys.",
    favoriteActivity: "Submerging until only nostrils are visible, waiting for drama.",
    favoriteHobby: "Cannonballing into quiet lagoons to soak spectators.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐☆☆ (Sweats pink cream through every fedora band)",
    brainPower: "50% nap preservation, 50% cabbage chewing",
    stats: {
      intelligence: "95 ripe watermelons",
      sleepiness: 85,
      pizzaCompatibility: 90,
      gamingSkill: 35,
      teaResistance: "Drinks river water by the bathtub",
      wifiDependency: "Medium",
      dancingAbility: "Underwater ballet prima ballerina"
    },
    scientificConfidence: 3.4,
    comparisonStats: {
      roaringPower: 89,
      snackCapacity: 98,
      napAbility: 88,
      danceSkill: 60,
      wifiStrength: 40,
      homeworkAvoidance: 92,
      randomness: 50,
      hatCompatibility: 20,
      formalwear: 50
    }
  },
  {
    id: "rhino",
    name: "Rhinoceros",
    emoji: "🦏",
    category: "jungle",
    fakeScientificName: "Chunky Unicornus Armatus",
    badge: "Tactical Armored Battle Cow",
    fakeWeight: "50 heavy cast-iron stoves",
    fakeHeight: "1 garden shed",
    fakeSpeed: "Charges at 50 km/h at harmless rocks that look suspicious",
    fakeDiet: "Thorny bushes, acacia stems, and crushed granola bars",
    fakeHabitat: "Dusty plains where rocks need charging at",
    fakeLifespan: "Armored plated indefinitely",
    funnyFact: "Rhinos have such poor eyesight they frequently charge at large boulders thinking they are rude strangers refusing to say hello.",
    specialAbility: "Can mistake a parked Volkswagen Beetle for a worthy romantic partner.",
    favoriteActivity: "Taking mud baths to achieve optimal crustiness.",
    favoriteHobby: "Polishing horn against unsuspecting termite mounds.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐⭐⭐⭐☆ (Horn impales hat straight through center)",
    brainPower: "85% charging velocity, 15% checking eyesight",
    stats: {
      intelligence: "45 muddy pebbles",
      sleepiness: 65,
      pizzaCompatibility: 79,
      gamingSkill: 25,
      teaResistance: "Crushes teacup under chin",
      wifiDependency: "Low",
      dancingAbility: "Stomping heavy metal headbang"
    },
    scientificConfidence: 2.3,
    comparisonStats: {
      roaringPower: 80,
      snackCapacity: 88,
      napAbility: 70,
      danceSkill: 45,
      wifiStrength: 30,
      homeworkAvoidance: 85,
      randomness: 60,
      hatCompatibility: 15,
      formalwear: 35
    }
  },
  {
    id: "flamingo",
    name: "Flamingo",
    emoji: "🦩",
    category: "birds",
    fakeScientificName: "Legbalance Pinkus",
    badge: "One-Legged Yoga Instructor",
    fakeWeight: "3 pink feathers and a plastic lawn ornament",
    fakeHeight: "1 tall standing lamp",
    fakeSpeed: "Stilt-walking elegance",
    fakeDiet: "Pink shrimp, strawberry milk, and aesthetic pride",
    fakeHabitat: "Alkaline lakes and suburban Florida front lawns",
    fakeLifespan: "Until the lawn mower runs over its plastic cousin",
    funnyFact: "Flamingos stand on one leg because if they lift the other leg up too, they would simply fall flat on their faces.",
    specialAbility: "Can drink upside-down while judging nearby geese.",
    favoriteActivity: "Striking runway model poses for ungrateful ducks.",
    favoriteHobby: "Refusing to put the other foot down under any circumstances.",
    difficultyFindingHat: "⭐⭐⭐☆☆☆☆☆☆☆ (Looks fabulous in a pink sunbonnet)",
    brainPower: "80% balancing on one stick, 20% maintaining hot pink color",
    stats: {
      intelligence: "60 pink prawns",
      sleepiness: 50,
      pizzaCompatibility: 65,
      gamingSkill: 72,
      teaResistance: "Drinks iced raspberry hibiscus",
      wifiDependency: "High (curating Instagram feed)",
      dancingAbility: "Flamenco world champion"
    },
    scientificConfidence: 3.7,
    comparisonStats: {
      roaringPower: 35,
      snackCapacity: 60,
      napAbility: 65,
      danceSkill: 98,
      wifiStrength: 80,
      homeworkAvoidance: 75,
      randomness: 80,
      hatCompatibility: 92,
      formalwear: 95
    }
  },
  {
    id: "hedgehog",
    name: "Hedgehog",
    emoji: "🦔",
    category: "nobody_asked",
    fakeScientificName: "Needle Mouse Spiky",
    badge: "Self-Propelled Pincushion",
    fakeWeight: "1 small grapefruit",
    fakeHeight: "Half an apple",
    fakeSpeed: "Tippy-tappy sprint at 3:00 AM",
    fakeDiet: "Insects, cat kibble, and small stolen grapes",
    fakeHabitat: "Garden hedgerows and empty cardboard toilet rolls",
    fakeLifespan: "Until it uncurls into a smile",
    funnyFact: "Hedgehogs roll into spiky balls not for protection, but because it is the most comfortable way to ignore text messages.",
    specialAbility: "Can turn into an impenetrable spiky tennis ball when asked to socialize.",
    favoriteActivity: "Getting head stuck in miniature paper cups.",
    favoriteHobby: "Running 14 miles on a squeaky exercise wheel while human tries to sleep.",
    difficultyFindingHat: "⭐⭐⭐⭐⭐⭐☆☆☆☆ (Spikes puncture through the brim instantly)",
    brainPower: "10% snuffling, 90% defensive sphere geometry",
    stats: {
      intelligence: "40 spiky toothpicks",
      sleepiness: 75,
      pizzaCompatibility: 88,
      gamingSkill: 88,
      teaResistance: "Carefully sips lukewarm chamomile with tiny paws",
      wifiDependency: "Medium (downloads running wheel apps)",
      dancingAbility: "Sonic spin dash"
    },
    scientificConfidence: 2.8,
    comparisonStats: {
      roaringPower: 20,
      snackCapacity: 50,
      napAbility: 85,
      danceSkill: 70,
      wifiStrength: 60,
      homeworkAvoidance: 95,
      randomness: 82,
      hatCompatibility: 40,
      formalwear: 60
    }
  }
];

const USELESS_FACTS = [
  "Scientists have confirmed that zebras are just regular horses wearing designer pajamas.",
  "Penguins wear tuxedos because they are permanently prepared for an unexpected boardroom meeting.",
  "Elephants have excellent memories, but still forget why they walked into the kitchen.",
  "Scientists are currently unsure whether a giraffe can use a selfie stick without air traffic control clearance.",
  "Snails are actually quite fast if you measure their progress relative to continental drift.",
  "Fish are world-class swimmers, but universally terrible at riding bicycles.",
  "A group of flamingos is legally classified as an aesthetic inconvenience.",
  "Lions spend 23 hours a day sleeping because being majestic is emotionally exhausting.",
  "Tigers count their stripes every morning. If they lose count, they have to restart from the tail.",
  "Pandas were originally printed in black and white because the printer ran out of yellow cartridge.",
  "Ducks do not actually quack; they are reciting medieval French philosophy backwards.",
  "Frogs swallow by pulling their eyeballs into their mouths to physically push the food down.",
  "Crocodiles shed tears only when someone spoils the ending of their favorite telenovela.",
  "Chickens retain memory of being dinosaurs and are currently biding their time.",
  "Sloths once tried running a marathon, but the timer expired during the Bronze Age.",
  "Monkeys can type out Shakespeare if given infinite bananas and an ergonomic mousepad.",
  "Hippopotamus milk is pink, which means nature is basically running a strawberry milkshake dispenser.",
  "Unicorn horns pick up free 5G signals, but mythical creatures refuse to pay roaming fees.",
  "Dinosaurs did not go extinct from an asteroid; they simply refused to do their chores and vanished.",
  "Turtles can live for 200 years purely out of stubbornness to outlive their landlords.",
  "Kangaroos carry emergency peanut butter sandwiches in their pouches for unexpected layovers.",
  "Parrots repeat what you say because they are secretly reporting your gossip to local pigeons.",
  "Koalas sleep 22 hours a day because eucalyptus leaves take too long to digest emotionally.",
  "Bears hibernate because they cannot deal with holiday family small talk.",
  "Ants can lift 50 times their own body weight, but still struggle to open plastic cereal bags.",
  "Bees communicate through dance because texting with tiny wings leads to auto-correct disasters.",
  "Camels store water in their humps, but also keep spare phone chargers in the other hump.",
  "Owls can rotate their heads 270 degrees just to avoid making eye contact with neighbors.",
  "Octopuses have three hearts: one for blood, one for drama, and one for holding grudges.",
  "Hamsters run on exercise wheels because they believe they are generating electricity for the matrix."
];

const QUIZ_QUESTIONS = [
  {
    question: "What does a giraffe primarily use its long neck for?",
    answers: [
      { text: "Reaching nutritious acacia leaves", correct: false, comment: "Too sensible! Real scientists would never." },
      { text: "Inspecting Wi-Fi signal strength above cloud level", correct: true, comment: "Correct! Giraffes are nature's 5G repeaters." },
      { text: "Looking for its misplaced fedora hat", correct: false, comment: "Close, but giraffes gave up on hats in 1994." },
      { text: "Sneaking peeks at second-floor hotel breakfast buffets", correct: false, comment: "Plausible, but not the primary scientific reason." }
    ]
  },
  {
    question: "Why do penguins always wear tuxedos?",
    answers: [
      { text: "Natural camouflage against oceanic predators", correct: false, comment: "Boring textbook nonsense. Disqualified!" },
      { text: "They were invited to a gala in 1842 and never took it off", correct: true, comment: "Spot on! The party was in Vienna and was fabulous." },
      { text: "To intimidate casual seagulls in hoodies", correct: false, comment: "A side benefit, but not the main intention." },
      { text: "Because Antarctic dry cleaners give loyalty discounts", correct: false, comment: "Dry cleaners refuse fish grease vouchers." }
    ]
  },
  {
    question: "How fast is a snail when properly motivated?",
    answers: [
      { text: "Fast enough to beat continental drift", correct: true, comment: "Accurate! Tectonic plates fear the snail." },
      { text: "0.03 miles per hour", correct: false, comment: "Gross, real numbers. We don't do that here." },
      { text: "Speed of light, but backwards", correct: false, comment: "That's physics, not snailology." },
      { text: "Mach 2 if you put strawberry jam on its shell", correct: false, comment: "Jam only makes it sticky, not supersonic." }
    ]
  },
  {
    question: "What is an elephant's greatest intellectual weakness?",
    answers: [
      { text: "Cannot solve quadratic equations", correct: false, comment: "Actually, elephants are decent at calculus." },
      { text: "Forgets email passwords within 4 seconds of resetting them", correct: true, comment: "Verified by 0 out of 10 IT security specialists!" },
      { text: "Terrified of very polite mice", correct: false, comment: "Mice are too polite to cause drama." },
      { text: "Cannot remember where it left its spectacles", correct: false, comment: "Elephants wear monocles, obviously." }
    ]
  },
  {
    question: "What happens when a sloth experiences an adrenaline rush?",
    answers: [
      { text: "It blinks its left eye 3 seconds faster than usual", correct: true, comment: "Brilliant! Sloth cardiologists were stunned by this speed." },
      { text: "It sprints at 45 mph through the jungle", correct: false, comment: "Too energetic. Sloths would rather dissolve." },
      { text: "It falls off the branch into a hammock", correct: false, comment: "That is regular daily routine, not adrenaline." },
      { text: "It orders express shipping on fresh moss", correct: false, comment: "Sloths don't trust modern postal couriers." }
    ]
  }
];

const CHIMERA_DATA = {
  prefixes: [
    "Flying", "Angry", "Professional", "Sleepy", "Confused", "Cybernetic", 
    "Invisible", "Dramatic", "Overcaffeinated", "Sarcastic", "Tax-Evading", 
    "Miniature", "Philosophical", "Submerged", "Disco-Dancing", "Polite"
  ],
  nouns: [
    "Potato", "Banana", "Wi-Fi", "Toaster", "Espresso", "Pancake", 
    "Sofa", "Tuxedo", "Bicycle", "Avocado", "Submarine", "Laser", 
    "Accordion", "Waffle", "Briefcase", "Disco"
  ],
  creatures: [
    { name: "Lion", emoji: "🦁" },
    { name: "Elephant", emoji: "🐘" },
    { name: "Giraffe", emoji: "🦒" },
    { name: "Penguin", emoji: "🐧" },
    { name: "Tiger", emoji: "🐯" },
    { name: "Panda", emoji: "🐼" },
    { name: "Sloth", emoji: "🦥" },
    { name: "Duck", emoji: "🦆" },
    { name: "Snail", emoji: "🐌" },
    { name: "Crocodile", emoji: "🐊" },
    { name: "Chicken", emoji: "🐔" },
    { name: "Monkey", emoji: "🐒" },
    { name: "Frog", emoji: "🐸" },
    { name: "Zebra", emoji: "🦓" },
    { name: "Kangaroo", emoji: "🦘" },
    { name: "Turtle", emoji: "🐢" },
    { name: "Unicorn", emoji: "🦄" },
    { name: "Dinosaur", emoji: "🦖" }
  ],
  habitats: [
    "Under hotel room beds with poor carpet maintenance",
    "Inside an abandoned espresso machine in Zurich",
    "Between two couch cushions during movie night",
    "High-speed commuter trains without valid tickets",
    "At the bottom of lukewarm tea cups",
    "The 404 Not Found error page of the Internet",
    "A cardboard box labeled 'Miscellaneous Cables'",
    "The VIP lounge of a supermarket bakery"
  ],
  diets: [
    "Cold pizza crusts, lost USB sticks and raw drama",
    "99% unearned confidence and stale potato chips",
    "Crushed garlic bread and spilled sparkling water",
    "Old grocery receipts and optimistic resolutions",
    "Marshmallows dipped in pure espresso",
    "Cloud vapor and broken Wi-Fi promises"
  ],
  superpowers: [
    "Can mute any Zoom meeting by sheer force of disappointment.",
    "Causes nearby toast to land butter-side down 100% of the time.",
    "Can remember any 90s pop song lyrics while forgetting own birthday.",
    "Generates a static electricity shock capable of charging an electric toothbrush.",
    "Can delay impending deadlines by barking backward at the calendar.",
    "Turns any polite conversation into a heated debate about sandwich geometry."
  ]
};

const RANDOM_RECHECK_FACTS = [
  {
    weight: "3.4 metric tons of unread emails",
    height: "2.1 ironing boards",
    speed: "Faster than an accidental reply-all",
    confidence: "0.2%",
    notes: "Telemetry recalculated using a wet noodle."
  },
  {
    weight: "Exactly 88 bowling balls and a shoe",
    height: "5 stackable garden chairs",
    speed: "Depends on whether snacks are visible",
    confidence: "1.7%",
    notes: "Verified by two hamsters and an intern."
  },
  {
    weight: "14 helium balloons (barely on the ground)",
    height: "0.8 lampposts",
    speed: "Speed of an ice cream cone melting on asphalt",
    confidence: "0.04%",
    notes: "Peer reviewed by an ornamental garden gnome."
  },
  {
    weight: "61 cans of sparkling seltzer",
    height: "4 acoustic guitar necks",
    speed: "Slower than downloading an operating system update on dial-up",
    confidence: "2.9%",
    notes: "Measurements taken while animal was pretending to be asleep."
  },
  {
    weight: "7 heavy cast-iron pans and a spatula",
    height: "11 smartphone screens laid end-to-end",
    speed: "Slightly faster than yesterday, but slower than tomorrow",
    confidence: "0.8%",
    notes: "NASA satellites were consulted; they politely hung up."
  }
];

// Attach to window for universal availability
if (typeof window !== "undefined") {
  window.UselessZooData = {
    ANIMALS,
    USELESS_FACTS,
    QUIZ_QUESTIONS,
    CHIMERA_DATA,
    RANDOM_RECHECK_FACTS
  };
}
